# Generated by Django 5.2.6 on 2025-10-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pliope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='propic',
            field=models.ImageField(blank=True, default='Media/default.png', null=True, upload_to='Media/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
