# Generated by Django 5.2.6 on 2025-11-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pliope', '0002_person_propic_alter_person_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesion',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
